### ISSUE TITLE
TODO list WebDAV support

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-next#3]
This issue should contain an overview of all issues that should be addressed/fixed before end of April 2022, in order to seamlessly integrate `clone` and `push` to WebDAV siblings, which might also require a `create-sibling-webav`.

### Outline of the current implementation strategy:

1. For each webdav-sibling with name `n`, create two remotes: `n-tree`, and `n-git`. The first is a git-annex special remote of type webdav with exporttree set to yes. The second is a `datalad-annex::`-special remote that points to the same location as `n-tree`.
2. Patch (via datalad-next) the push command to redirect pushes to a special remote with export-tree to `git annex export`, as described here: https://github.com/datalad/datalad/issues/3127. The export implementation could for example be done via `git annex export` or via something similar to `x-export-to-webdav`.
3. Define a publish dependency between both of them. Then pushing, for example, to `n-git` could autmatically trigger pushing to `n-tree`, which leads to an automated push of `n-tree`.
4. Integrate them with the new credential system.

### Work packages:

- [x] datalad contains a refactoring of `push` that isolates the actual data transport into `_transfer_data` (PR https://github.com/datalad/datalad/pull/6618).
- [ ] datalad_next contains a patch in `push_to_export_remote.py` that patches `_transfer_data`. There are currently two alternative patches in two branches and two PRs:
    -- Alternative1: PR #4: use x-export-to-webdav to implement the equivalent of `_push_data` for exporttree-remotes. This is most likely *TOO* specific and contains probably *TOO* much logic (subdatasets). But the existing code can probably be re-used in parts.
   -- Alternative2: PR #5: use plain `git annex export` to push `HEAD` to the remote. The current code does currently not perform all checks that `_push_data` implements. There might be no need for the checks, or there might be need for more checks and logic, for example w.r.t. subdatatasets. That depends on the position of `_push_data` in the `datalad push` logic, which I am not familiar with.

- [x] Ensure that the new credential system is used.
- [x] Add a `siblings-create-webdav` that will take a name-base and create two siblings: &lt;name-base&gt;`-tree`, which is a webdav special remote with `export-tree` set to `yes`, and &lt;name-base&gt;`-vcs`, which is a `datalad-annex::`-remote which points to the same location as the &lt;name-base&gt;`-tree` remote. This is done in PR #6 

### Authentication and credentials:

- https://github.com/mih/datalad-mihextras/issues/30: round up of issues that need to be fixed for VCS+Storage backends

- https://github.com/mih/datalad-mihextras/issues/28: check this out for credential handling in `x-export-to-webdav`

- https://github.com/datalad/datalad/issues/6451: describes an authentication scenario for webdav

- https://github.com/datalad/datalad/issues/5483: describes support for B2DROP which is webdav-based
