### ISSUE TITLE
datalad-core dependency tracker

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#629]
This issue lists all dependencies on the datalad-core package -- except for the command API.

The idea is not tracking how independent datalad-next is for user activities, but to track how entangled both code bases are, and which components of datalad-core are reused in datalad-next.

This list does not include dependency of runtime patches. A separate list below tracks dependencies of test implementations

A checked box indicates a once present, but now removed dependency

- [ ] `datalad.config.ConfigManager`
- [ ] `datalad.consts.PRE_INIT_COMMIT_SHA`
- [ ] `datalad.customremotes.RemoteError`
- [ ] `datalad.customremotes.SpecialRemote`
- [ ] `datalad.customremotes.main.main`
- [ ] `datalad.dataset.gitrepo.GitRepo`
- [ ] `datalad.distribution.dataset.Dataset`
- [ ] `datalad.distribution.dataset.require_dataset`
- [ ] `datalad.distribution.utils._yield_ds_w_matching_siblings`
- [ ] `datalad.interface.base.Interface`
- [ ] `datalad.interface.base.eval_results`
- [ ] `datalad.interface.common_opts.recursion_(flag|limit)`
- [ ] `datalad.interface.results.get_status_dict`
- [ ] `datalad.interface.utils.generic_result_renderer`
- [ ] `datalad.log.log_progress`
- [ ] `datalad.runner.Runner`
- [ ] `datalad.runner.GitRunner`
- [ ] `datalad.runner.ThreadedRunner`
- [ ] `datalad.runner.STDOUT_FILENO`
- [ ] `datalad.runner.STDERR_FILENO`
- [ ] `datalad.runner.utils.LineSplitter`
- [ ] `datalad.runner.KillOutput`
- [ ] `datalad.runner.NoCapture`
- [ ] `datalad.runner.Protocol`
- [ ] `datalad.runner.StdOutCapture`
- [ ] `datalad.runner.StdErrCapture`
- [ ] `datalad.runner.StdOutErrCapture`
- [ ] `datalad.runner.exception.CommandError`
- [ ] `datalad.support.annexrepo.AnnexRepo`
- [ ] `datalad.support.ansi_colors`
- [ ] `datalad.support.exceptions.CapturedException`
- [ ] `datalad.support.exceptions.IncompleteResultsError`
- [ ] `datalad.support.exceptions.NoDatasetFound`
- [ ] `datalad.support.extensions.register_config`
- [ ] `datalad.support.external_versions.external_versions`
- [ ] `datalad.support.gitrepo.GitRepo`
- [ ] `datalad.support.param.Parameter`
- [ ] `datalad.ui.ui`
- [ ] `datalad.utils.chpwd`
- [ ] `datalad.utils.check_symlink_capability`
- [ ] `datalad.utils.ensure_list`
- [ ] `datalad.utils.get_dataset_root`
- [ ] `datalad.utils.rmtree`
- [ ] `datalad.utils.on_linux|windows`

# backward compat with credentials

- [ ] `datalad.support.keyring_.keyring`
- [ ] `datalad.downloaders.CREDENTIAL_TYPES`
- [ ] `datalad.downloaders.providers.Providers`

# backward compat with `archive` remote

- [ ] `datalad.customremotes.archives.ArchiveAnnexCustomRemote`

### Tests

- [ ] `datalad.conftest.setup_package`
- [ ] ...
